version: '3.7'

services:

  web-rpg-game-postgres:
    image: "postgres:latest"
    restart: always
    container_name: "web-rpg-game-postgres"
    environment:
      POSTGRES_DB: "rpg-game-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
