server:
  port: 8090

spring:
  application:
    name: api-gateway

### gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      loadbalancer:
          use404=true:
      discovery:
        locator:
          enabled: true
      routes:
        # forum mapping
        - id: forum
          uri: lb://forum
          predicates:
            - Path=/forum/**
          filters:
            - RewritePath=/forum/(?<path>.*), /$\{path}

        # lobby mapping
        - id: lobby
          uri: lb://lobby
          predicates:
            - Path=/lobby/**
          filters:
            - RewritePath=/lobby/(?<path>.*), /$\{path}
          # auth-security mapping
        - id: auth-security
          uri: lb://auth-security
          predicates:
            - Path=/auth-security/**
          filters:
            - RewritePath=/auth-security/(?<path>.*), /$\{path}

logging:
  level:
    org.springframework.cloud.gateway: INFO