server:
  contextPath: /
  port: 8087 #${random.int[1024,65535]}


spring:
  #Application
  application:
    name: lobby

  #Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
  output.ansi.enabled: ALWAYS


game:
  amqp:
    matchmaking:
      queue: matchmaking
      exchange: matchmaking.exchange
      routingkey: matchmaking.routing.key
    group-matchmaking:
      queue: matchmaking
      exchange: matchmaking.exchange
      routingkey: group-matchmaking.routing.key