server:
  port: 8088 #${random.int[1024,65535]}


spring:
  #Application
  application:
    name: friend

  output.ansi.enabled: ALWAYS

#  #Discovery
#  cloud:
#    consul:
#      host: localhost
#      port: 8500




