server:
  contextPath: /
  port: 8084 #${random.int[1024,65535]}
#  servlet:
#    context-path: /forum

#logging:
  #level:
    #org:
      #hibernate:
        #type: trace
        #stat: debug

spring:
  #Application
  application:
    name: forum
  #Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
  output.ansi.enabled: ALWAYS

  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:forum-service-db-changelog.xml}
    #classpath:/forum-service-db-changelog.xml:

  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  #JPA
  datasource:
    url: jdbc:h2:mem:game-rpg-db;DB_CLOSE_DELAY=-1
    username: admin
    password:
    platform: h2 #added

