jwt.secret: reallysecretgoldkey12345678901111111111111111111111111111111111111111111111111111111111111111111111111111111
jwt.refreshExpirationMs: 3600000 #1000 * 60 * 60

server:
  port: 8081 #${random.int[1024,65535]}

spring:
  #Application
  application:
    name: forum
  main:
    allow-bean-definition-overriding: true
  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:forum-service-db-changelog.xml}
    #classpath:/forum-service-db-changelog.xml:

  h2:
    console:
      enable: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true

  #JPA
  datasource:
    url: jdbc:h2:mem:game-rpg-db;DB_CLOSE_DELAY=-1
    username: admin
    password:

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: none

  #Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "beans"
