server:
  port: 8081 #${random.int[1024,65535]}

spring:
  #Application
  application:
    name: forum

  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:forum-service-db-changelog.xml}

h2:
  console:
    enable: true
    path: /h2
    settings:
      trace: true
      web-allow-others: true

  #JPA
  datasource:
    url: jdbc:h2:mem:game-rpg-db;DB_CLOSE_DELAY=-1
    username: admin
    password:

#  #JPA
#  datasource:
#    url: jdbc:postgresql://localhost:5432/artist-db
#    username: postgres
#    password: 852456
#
#  jpa:
#    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false
#        ddl-auto: none

  #Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "beans"
